#+TITLE: ~C++~ Exercises
#+SETUPFILE: assignment-setup.org

* Does It Compile?

  In this section, we review the basic ~C++11~ syntax.  Select the one
  that generates a compile error.

  1.
     #+ATTR_LaTeX: :environment inparaenum
     - =int a;=
     - =int a3;=
     - =int a_3;=
     - =int 3a;=
  2.
     #+ATTR_LaTeX: :environment inparaenum
     - =int mon-said-it-is-an-ugly-name;=
     - =int monSaidItIsAnUglyName;=
     - =int mon_said_it_is_an_ugly_name;=
     - =int monsaiditisanuglyname;=
  3.
     #+ATTR_LaTeX: :environment inparaenum
     - =char a{127};=
     - =char a = 3;=
     - =char a{'a'};=
     - =char a{128};=
  4. Suppose we have declaration =int a = 0=.

     #+ATTR_LaTeX: :environment inparaenum
     - =++a = 3;=
     - =a++ = 3;=
     - =a = a + 3;=
     - =-a;=
  5.
     #+ATTR_LaTeX: :environment inparaenum
     - =int a[]{1, 2};=
     - =int a[3] = {1,2};=
     - =int a[2][]{1,2,3,4};=
     - =int a[][2]{1,2,3,4};=

* Run the Code (with your mind)

  Write down the output of the following code.  I omit the necessary
  header files and =main()= function for brevity.

  1.
     #+BEGIN_SRC cpp
char str[]{"Hello\0World!\n"};
cout << str << endl;
     #+END_SRC

  2.
     #+BEGIN_SRC cpp
int a = 3;
int* b = &a;
int& c = a;
printf("%d %d %d\n", a, *b, c);
(*b) = 4;
printf("%d %d %d\n", a, *b, c);
c = 40;
printf("%d %d %d\n", a, *b, c);
     #+END_SRC

  3.

     #+BEGIN_SRC cpp
int a = 0;
if (a = 3)
  cout << "foo" << endl;
else
  cout << "bar" << endl;
     #+END_SRC

  4.

     #+BEGIN_SRC cpp
int a = 0, b{3};
switch(a) {
  case 0: --b;
  case 1: ++b; break;
  case 2: b *= 3;
  default: b -= 4;
}
cout << b << endl;
     #+END_SRC

  5.

     #+BEGIN_SRC cpp
int end = 4;
for (int i = 0; i < end; ++i) {
  --end;
  cout << end << endl;
}
     #+END_SRC

  6.

     #+BEGIN_SRC cpp
string s{"12345678"};
cout << s.substr(1, 3) << endl;
s.replace(0, 1, "abcd");
cout << s << endl;
cout << s + "hello" << endl;
cout << s.c_str() << endl;
     #+END_SRC

  7.

     #+BEGIN_SRC cpp
int i;
while (cin >> i) {
  cout << i << endl;
}
     #+END_SRC

  8.

     #+BEGIN_SRC cpp
#define str(x) #x
#define glue(a,b) a ## b

glue(c,out) << str(Hello\nWor
                   ld!) << endl;
     #+END_SRC

* Show Me Your Code

  1. Please write a short ~C++~ program to investigate how the
     floating numbers are stored in memory.  /hint: we used the
     =union= to discuss how integer is stored/.
  2. Finish the =Complex= class

* COMMENT Dummy

# Local Variables:
# eval: (add-to-list 'org-latex-text-markup-alist '(verbatim . "\\cpp/%s/"))
# End:

#  LocalWords:  SETUPFILE toc usepackage newitem newenum paralist cpp
#  LocalWords:  newmintinline fontsize ATTR LaTeX inparaenum mon SRC
#  LocalWords:  monSaidItIsAnUglyName monsaiditisanuglyname eval
#  LocalWords:  alist
