#+TITLE: PPL -- Homework 5
#+SETUPFILE: setup.org
#+DATE: Due on Nov 10

#+BEGIN_abstract
Homework 5 covers object-oriented programming.
#+END_abstract

* Requirement

  1. Separate your declaration into =.h= and =.cpp=.
  2. Zip all your files into one file named
     *your-auburn-username.zip*, e.g., zzg0009.zip.  Improper naming
     incurs 10 points penalty.
  3. Accepted languages are =C++= and =Python=.

* ADT =queue=

   (*40 points*) /Implement/ a first-in first-out (FIFO) =queue=
   class.  Public interface includes =push=, =pop_front=, =size= and
   =empty=.  You may assume that the data stored in =queue= is
   /integer/.  Signature of the interface is as follows.

   For C++,

   #+BEGIN_SRC cpp
int push(int);
int pop_front();
int size();
bool empty();
   #+END_SRC

   For Python,

   #+BEGIN_SRC python
def push(val): return val
def pop_front(): pass
def size(): pass
def empty(): pass
   #+END_SRC

* ADT =complex=

  (*60 points*) Implement an ADT for complex numbers, including
  operations for addition, substraction, multiplication and divisions,
  and getters and setters for image and real part.  Assume that the
  image and real part are floating numbers.  Math operations need to
  be implemented through operator overloading.
